version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    env_file: .env
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_ROOT_PASSWORD
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local