version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQLDB_ROOT_PASSWORD}" ]
      retries: 3
      timeout: 5s

volumes:
  db: